version: '3'
services: 
  web:
    build: .
    ports: 
    - 8080:8080
    depends_on:
    - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    expose:
    - 9200
    - 9300
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
