version: '3'
services: 
  picture_data:
    build: ./picture_info_store/
    environment:
    - ELASTICSEARCH_CLUSTERNAME=elasticsearch
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_PORT=9300
    expose: 
    - 8080
    depends_on:
    - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    expose:
    - 9200
    - 9300
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  
  picture_store:
    build: ./picture_store/
    expose: 
      - 8080
  gateway:
    build: ./gateway/
    ports:
      - 8080:8080
